[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB
board_build.flash_mode = dio
board_build.arduino.memory_type = qio_opi

build_flags = 
  -I include
  -DLV_CONF_INCLUDE_SIMPLE
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

platform_packages =
  tool-esptoolpy @ platformio/tool-esptoolpy@~2.40900.0

lib_deps =
  lvgl/lvgl@^8.3.4
  mathieucarbou/ESPAsyncWebServer
